---
#
# Ansible managed
#
repository:
  description: Install and configure umask on your system.
  homepage: https://buluma.github.io/
  topics: umask, ansible, molecule, tox, playbook, hacktoberfest
